apiVersion: apps/v1
kind: Deployment
metadata:
  name: totally-stable-service
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-crashloop-depl
  template:
    metadata:
      labels:
        name: nginx-crashloop-depl
    spec:
      containers:
      - command:
        - which
        - foobar
        image: nginx:1.21
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            memory: "16Mi"
            cpu: "100m"
          limits:
            memory: "32Mi"
            cpu: "200m"
