---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kspan
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-role-binding-kspan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: kspan
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kspan
  namespace: kube-system
  name: kspan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kspan
  template:
    metadata:
      labels:
        app: kspan
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: kspan
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
      containers:
        - image: ghcr.io/honeycombio/kspan/kspan:0.2.1
          name: kspan
          args:
            - --otlp-addr=kubernetes-monitoring-grafana-agent.monitoring.svc.cluster.local:4317
          resources:
            limits:
              cpu: 100m
              memory: 40Mi
            requests:
              cpu: 100m
              memory: 30Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
