# This is the configuration for Kind
# It simply makes a Kubernetes cluster with three nodes, one of which is the control-plane
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: worker
  - role: worker
