datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: 	http://prometheus-server.monitoring.svc:80
        isDefault: true
        basicAuth: true
        basicAuthUser: promuser
        secureJsonData:
          basicAuthPassword: prometheuspassword

      - name: Loki
        type: loki
        url: 	http://loki-gateway.monitoring.svc:80
        basicAuth: true
        basicAuthUser: loki
        jsonData:
          httpHeaderName1: X-Scope-OrgID
        secureJsonData:
          basicAuthPassword: lokipassword
          httpHeaderValue1: "1"

      - name: Tempo
        type: tempo
        url: 	http://tempo.monitoring.svc:3100
