cluster:
  name: windycity_devfest_demo

externalServices:
  prometheus:
    host: http://prometheus-server.monitoring.svc:80
    basicAuth:
      username: promuser
      password: prometheuspassword
    queryEndpoint: /api/v1/query
    writeEndpoint: /api/v1/write
  loki:
    host: http://loki.monitoring.svc:3100
    tenantId: 1
    basicAuth:
      username: loki
      password: lokipassword
  tempo:
    host: tempo.monitoring.svc:4317

opencost:
  prometheus:
    external:
      url: http://prometheus-server.monitoring.svc:80/api/v1

traces:
  enabled: true

grafana-agent:
  agent:
    extraPorts:
      - name: "otlp-grpc"
        port: 4317
        targetPort: 4317
        protocol: "TCP"
      - name: "otlp-http"
        port: 4318
        targetPort: 4318
        protocol: "TCP"

extraConfig: |
  discovery.relabel "apiserver" {
    targets = discovery.kubernetes.services.targets
    rule {
      source_labels = ["__meta_kubernetes_namespace"]
      regex = "default"
      action = "keep"
    }
    rule {
      source_labels = ["__meta_kubernetes_service_name"]
      regex = "kubernetes"
      action = "keep"
    }
    rule {
      source_labels = ["__meta_kubernetes_service_port_name"]
      regex = "https"
      action = "keep"
    }
  }

  prometheus.scrape "apiserver" {
    job_name   = "integrations/kubernetes/apiserver"
    targets    = discovery.relabel.apiserver.output
    scheme     = "https"
    bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
    tls_config {
      insecure_skip_verify = true
    }
    clustering {
      enabled = true
    }
    forward_to = [prometheus.remote_write.grafana_cloud_prometheus.receiver]
  }
