# This is the values file that determines how we are configuring Kubernetes Monitoring.

# Set the cluster name, this is added as a label to all telemetry data
cluster:
  name: windycity_devfest_demo

# Define the external services to send data to
externalServices:
  prometheus:
    host: http://prometheus-server.monitoring.svc:80
    basicAuth:
      username: promuser
      password: prometheuspassword
    queryEndpoint: /api/v1/query
    writeEndpoint: /api/v1/write
  loki:
    host: http://loki.monitoring.svc:3100
    tenantId: 1
    basicAuth:
      username: loki
      password: lokipassword
  tempo:
    host: tempo.monitoring.svc:4317
    tlsOptions: |-
      insecure             = true
      insecure_skip_verify = true

# We don't care about cost for a kind cluster, disable
opencost:
  enabled: false

# Enable apiserver metrics, but disable cost metrics
metrics:
  apiserver:
    enabled: true
  cost:
    enabled: false

# Enable the ability to ingest traces and send them to Tempo
traces:
  enabled: true

# Tell the Gafana Agent to open up these ports, which are used when traces are
# sent to the agent.
grafana-agent:
  agent:
    extraPorts:
      - name: "otlp-grpc"
        port: 4317
        targetPort: 4317
        protocol: "TCP"
      - name: "otlp-http"
        port: 4318
        targetPort: 4318
        protocol: "TCP"
