cluster:
  name: windycity_devfest_demo

externalServices:
  prometheus:
    host: http://prometheus-server.monitoring.svc:80
    basicAuth:
      username: promuser
      password: prometheuspassword
    queryEndpoint: /api/v1/query
    writeEndpoint: /api/v1/write
  loki:
    host: http://loki.monitoring.svc:3100
    tenantId: 1
    basicAuth:
      username: loki
      password: lokipassword
  tempo:
    host: tempo.monitoring.svc:4317
    tlsOptions: |-
      insecure             = true
      insecure_skip_verify = true

opencost:
  enabled: false

metrics:
  apiserver:
    enabled: true
  cost:
    enabled: false

traces:
  enabled: true

grafana-agent:
  agent:
    extraPorts:
      - name: "otlp-grpc"
        port: 4317
        targetPort: 4317
        protocol: "TCP"
      - name: "otlp-http"
        port: 4318
        targetPort: 4318
        protocol: "TCP"
