tempoQuery:
  ingrss:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: tempo-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
      kubernetes.io/ingress.class: nginx
